version: 0.2

env:
  variables:
    s3_output: "maciejmalak.ml"
    hugo_version: "0.72.0"
    hugo_package: "hugo_0.72.0_Linux-64bit.deb"

phases:
  install:
    commands:
      # - apt-get update && apt-get install sudo -y
      - wget "https://github.com/gohugoio/hugo/releases/download/v0.72.0/hugo_0.72.0_Linux-64bit.deb"
      - dpkg -i hugo_0.72.0_Linux-64bit.deb
    finally:
      - hugo version
  build:
    commands:
      - hugo
      # - cd public && aws s3 sync . s3://${s3_output} --delete --acl public-read
    finally:
      - echo "Script finished running"