baseurl = "http://maciejmalak.ml"
title = "MaciejMalak"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Maciej"

googleAnalytics = "UA-169797222-1"

[params]
    author = "Maciej Malak"
    info = "Software Engineer | AWS | Android | Technical Author"
    description = "description"
    keywords = "blog,developer,personal,software engineer,monkeydevs,poland,programming,blog,tutorials,blog posts"
    avatarurl = "images/maciej.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "For all business inquiries please contact me at hellomonkeydevs@gmail.com. I'm based in Wrocław, Poland."
    hideFooter = true
    hideCredits = true
    hideCopyright = true

    rtl = false

    # math = true
    # custom_css = ["css/custom.css"]

# Social links
[[params.social]]
      name = "Medium.com"
      icon = "fab fa-medium fa-2x"
      weight = 1
      url = "https://medium.com/@maciekmalak"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/maciejmalak/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 3
    url = "https://github.com/xavarius/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 4
    url = "https://twitter.com/MonkeyDevsPl"

# Menu links
[[menu.main]]
    name = "What I do"
    weight = 1
    url  = "https://www.linkedin.com/in/maciejmalak/"
[[menu.main]]
    name = "I'm writting about tech"
    weight = 2
    url  = "https://medium.com/@maciekmalak"
