baseurl = "http://www.maciejmalak.ml"
title = "MaciejMalak"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Maciej"

[params]
    author = "Maciej Malak"
    info = "Software Engineer | AWS | Android | Technical Author"
    description = "This is my description lalalalallala"
    keywords = "blog,developer,personal"
    avatarurl = "images/maciej.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "For all business inquiries please contact me at hellomonkeydevs@gmail.com"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/xavarius/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/MonkeyDevsPl"
[[params.social]]
      name = "LinkedIn"
      icon = "fab fa-linkedin fa-2x"
      weight = 3
      url = "https://twitter.com/MonkeyDevsPl"
[[params.social]]
      name = "Medium.com"
      icon = "fab fa-medium fa-2x"
      weight = 3
      url = "https://twitter.com/MonkeyDevsPl"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
